### ISSUE TITLE
PAR generating error

### ISSUE THREAD

**Issue by guangleibao** [oracle/bmcs-java-sdk#18]
The timeExpire parameter in ObjectStorageClient.createPreauthenticatedRequest is Date type, it's pretty safe. When it comes to JSON handling it should NOT have number or string error, but it has. Something went wrong?

------------------------------------------------------------------------------------------------
Caused by: com.oracle.bmc.model.BmcException: (400, InvalidJSON, false) PAR expiration in request body JSON must be of type number, but is STRING (opc-request-id: 2d2962fa-be55-07cd-889d-4ad131c1dab8)
        at com.oracle.bmc.http.internal.ResponseHelper.throwIfNotSuccessful(ResponseHelper.java:91)
        at com.oracle.bmc.http.internal.ResponseConversionFunctionFactory$ValidatingParseResponseFunction.apply(ResponseConversionFunctionFactory.java:87)
        at com.oracle.bmc.http.internal.ResponseConversionFunctionFactory$ValidatingParseResponseFunction.apply(ResponseConversionFunctionFactory.java:83)
        at com.oracle.bmc.objectstorage.internal.http.CreatePreauthenticatedRequestConverter$1.apply(CreatePreauthenticatedRequestConverter.java:88)
        at com.oracle.bmc.objectstorage.internal.http.CreatePreauthenticatedRequestConverter$1.apply(CreatePreauthenticatedRequestConverter.java:79)
        at com.oracle.bmc.objectstorage.ObjectStorageClient.createPreauthenticatedRequest(ObjectStorageClient.java:197)

**Comment by priteshkp** [comment]
Hi Guanglei,
   thanks for reporting this, we're taking a look and will get back to you.

**Comment by priteshkp** [comment]
Hi Guanglei,
  this issue should be resolved, could you try again and let us know if you're still hitting the issue?  Thanks,
Pritesh

**Comment by guangleibao** [comment]
Hi Pritesh,

I tested against both us-phoenix-1 and us-ashburn-1. The issue is solved. I can get the URI for example: /p/zlqeMXXXXXXXXXXXXX2arJkC0/n/<tenancy>/b/<bucket>/o/<object>. Thank you.

Before we close this issue, could I ask one more question which is since we can get the PAR URI, but what is the complete https URL for the specific object? I cannot found it in API nor in console.

**Comment by jodoglevy** [comment]
Hi Guanglei,
Regarding your follow up question, I've reached out to the Object Storage team and asked them to respond here.

**Comment by guangleibao** [comment]
Hi Guys,

I figured it out. The URL should be completed by https://objectstorage.[region-code].oraclecloud.com

Thank you.
